blog/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from . import views
from blog.sitemap import ArticleSitemap

app_name = 'blog'

urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list,name='post_list_by_tag'),
    # path('', views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_details, name='post_detail'),
    path('<int:post_id>/share/',views.post_share ,name='post_share'),
    path('<slug:slug>/comment/', views.post_comment, name='post_comment'),
    path('sitemap.xml', sitemap, {'sitemaps': {'article' : ArticleSitemap}},
     name='django.contrib.sitemaps.views.sitemap'),
    path('search/', views.post_search, name='post_search'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.postgres.search import SearchVector


# Create your models here.
class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF','Draft'
        PUBLISHED = 'PB','Published'
    
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    desc = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length=2,choices=Status.choices, default=Status.DRAFT)
    tags = TaggableManager()
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now = True)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False , widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','body']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
        
class SearchForm(forms.Form):
    query = forms.CharField()
    

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.views.decorators.http import require_POST
from django.contrib import messages
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank




# Create your views here.
def post_list(request,tag_slug=None):
    post_list = Post.objects.all()
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    
    paginator = Paginator(post_list,2)
    page_number = request.GET.get('page',1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'posts':posts,'tag':tag})

# class PostListView(ListView):
#     model = Post
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/post/list.html'
    
    

def post_details(request,year,month,day,slug):
    post = get_object_or_404(Post,
                             publish__year = year,
                             publish__month = month,
                             publish__day = day,
                             slug = slug)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_id = post.tags.values_list('id',flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags')
    print(similar_posts)
    
    return render(request,'blog/post/detail.html',{'post':post,'comments':comments,'form':form,'similar_posts':similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

            messages.success(request, "Your comment has been added!")

            return redirect(
                'blog:post_detail',
                year=post.publish.year,
                month=post.publish.month,
                day=post.publish.day,
                slug=post.slug
            )

    return redirect(
        'blog:post_detail',
        year=post.publish.year,
        month=post.publish.month,
        day=post.publish.day,
        slug=post.slug
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_vector = SearchVector('title', 'desc')
            search_query = SearchQuery(query, config='english')

            results = (
                Post.objects
                .annotate(
                    search=search_vector,
                    rank=SearchRank(search_vector, search_query)
                )
                .filter(search=search_query)
                .order_by('-rank')
            )

    return render(
        request,
        'blog/post/search.html',
        {'form': form, 'query': query, 'results': results}
    )

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
        integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Global Styles -->
    <style>
        body {
            background-color: #f8f9fa;
            font-family: "Segoe UI", sans-serif;
        }

        /* NAVBAR ANIMATIONS */
        .navbar-brand {
            transition: 0.3s;
        }

        .navbar-brand:hover {
            color: #0d6efd !important;
            transform: translateY(-2px);
        }

        .nav-link {
            font-weight: 500;
            transition: 0.2s;
        }

        .nav-link:hover {
            color: #0d6efd !important;
            transform: translateX(3px);
        }

        i {
            font-size: 1.2rem;
            color: #0d6efd;
        }

        /* FOOTER TEXT */
        footer p {
            font-size: 0.9rem;
        }

        /* PAGE SPACING */
        .main-container {
            min-height: 70vh;
            padding-top: 2rem;
        }

        /* Offcanvas header color */
        .offcanvas-title {
            color: #0d6efd;
        }

        .comment-card {
            transition: 0.2s;
        }

        .comment-card:hover {
            transform: translateY(-3px);
            background-color: #f1f5ff;
            border-color: #0d6efd56;
        }
    </style>
</head>

<body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm py-3 sticky-top">
        <div class="container">

            <a class="navbar-brand fw-bold text-primary fs-4" href="{% url 'blog:post_list' %}">
                <i class="fa-solid fa-blog"></i> BlogPost
            </a>

            <!-- Mobile Toggle -->
            <button class="btn btn-outline-primary d-lg-none" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#mobileMenu">
                ☰ Menu
            </button>

            <!-- Desktop Menu -->
            <div class="collapse navbar-collapse d-none d-lg-block">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-2">
                        <a class="nav-link" href="{% url 'blog:post_list' %}"><i class="fa-regular fa-house"></i>
                            Home</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link" href="#"><i class="fa-regular fa-address-card"></i> About</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a class="nav-link" href="#"><i class="fa-regular fa-address-book"></i> Contact</a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>

    <!-- MOBILE OFFCANVAS -->
    <div class="offcanvas offcanvas-start" tabindex="-1" id="mobileMenu">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title fw-bold">Menu</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
        </div>

        <div class="offcanvas-body">
            <ul class="navbar-nav">
                <li class="nav-item my-2">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Home</a>
                </li>
                <li class="nav-item my-2">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item my-2">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>

    <!-- MAIN CONTENT -->
    <div class="container main-container">
        {% block content %}{% endblock %}
    </div>

    <!-- FOOTER -->
    <footer class="mt-5 bg-light border-top">
        <div class="container py-4 text-center">
            <p class="text-muted mb-1">
                © {% now "Y" %} MyBlog — All Rights Reserved
            </p>
            <p class="text-primary fw-bold">
                Built with Django & Bootstrap ❤️
            </p>
        </div>
    </footer>

    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

blog/templates/blog/post/comment.html
<!-- blog/post/comment.html -->

{% extends "blog/base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Add a comment for "{{ post.title }}"</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="container py-4">

    <!-- Success Messages -->
    {% if messages %}
    <div class="mt-3">
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show shadow-sm fw-semibold" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Back Button -->
    <a href="{% url 'blog:post_list' %}" class="btn btn-outline-secondary mb-4">
        ← Back to Posts
    </a>

    <div class="row justify-content-between">
        <!-- Post Card -->
        <div class="card shadow-lg border-0 mb-5 rounded-4  col-md-8 ">
            <div class="card-body p-4">
                <h1 class="card-title mb-3">{{ post.title }}</h1>

                <p class="text-muted">
                    <small>
                        Published {{ post.publish|date:"M d, Y" }} •
                        By <strong>{{ post.author }}</strong>
                    </small>
                </p>

                <hr>

                <div class="content fs-5 mt-4 lh-lg">
                    {{ post.desc | markdown|linebreaks }}
                </div>
            </div>
        </div>
        <div class="mb-5 col-md-3">
            <h2 class="mb-2">Similar Posts</h2>
            {% for post in similar_posts%}
            <a href="{{post.get_absolute_url}}">{{post.title}} - {{post.same_tags}}</a>
            {% empty %}
            <p>No data similar_post</p>
            {% endfor %}
        </div>
    </div>


    <!-- Share Button -->
    <div class=" mb-5">
        <a href="{% url 'blog:post_share' post.id %}" class="btn btn-danger px-4 rounded-pill">
            <i class="bi bi-send"></i> Share Post
        </a>
    </div>


    <!-- Comments Section -->
    <div class="card shadow-sm border-0 rounded-4 mb-5">
        <div class="card-body p-4">

            <h3 class="mb-4 fw-bold">
                {{ comments.count }} Comment{{ comments.count|pluralize }}
            </h3>

            <!-- Comment List -->
            {% for comment in comments %}
            <div class="d-flex mb-4 p-3 border rounded bg-light comment-card">
                <div class="me-3">
                    <div class="rounded-circle bg-primary text-white d-flex align-items-center justify-content-center shadow"
                        style="width: 50px; height: 50px; font-size: 1.2rem; font-weight: 600;">
                        {{ comment.name|slice:":1" | upper }}
                    </div>
                </div>
                <div>
                    <h6 class="mb-1 fw-semibold">{{ comment.name }}</h6>
                    <p class="mb-0 text-muted small">
                        {{ comment.created|date:"M d, Y • H:i" }}
                    </p>
                    <p class="mt-2">{{ comment.body }}</p>
                </div>
            </div>

            {% empty %}
            <p class="text-muted fst-italic">No comments yet. Be the first to comment!</p>
            {% endfor %}

            <hr>

            <!-- Comment Form -->
            <h4 class="mt-4 mb-3 fw-bold">Leave a Comment</h4>

            <form action="{% url 'blog:post_comment' post.slug %}" method="post" class="mt-3">
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                    <label class="form-label fw-semibold">{{ field.label }}</label>
                    {{ field }}

                    {% if field.errors %}
                    <div class="text-danger small">{{ field.errors.0 }}</div>
                    {% endif %}
                </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary px-4 rounded-pill">
                    Post Comment
                </button>
            </form>

        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/post/latest_post.html
{% load blog_tags %}
<ul>
    {% for post in show_latest_posts %}
    <li>
        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
<div class="container py-4">
    <h1 class="mb-5 text-center">Latest Posts</h1>
    <div class="text-center mb-5">
        <form action="{% url 'blog:post_search' %}" method="get" class="d-inline-flex">
            <input type="text" name="query" class="form-control me-2" placeholder="Search posts...">
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
    </div>

    <div class="row">
        {% for post in posts %}
        <div class="col-md-6 mb-4">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h4 class="card-title">{{ post.title }}</h4>

                    <p class="text-muted mb-2">
                        <small>
                            Published {{ post.publish|date:"M d, Y" }}
                            by {{ post.author }}
                        </small>
                    </p>

                    <p class="card-text">
                        {{ post.desc| markdown | truncatechars_html:30}}
                    </p>

                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-sm mb-2">
                        Read More →
                    </a>
                </div>
            </div>

            <p class="tags mb-0">
                <small>
                    Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>{% if not forloop.last %}, {% endif %}
                    {% empty %}
                    No tags
                    {% endfor %}
                </small>
            </p>
        </div>
        {% empty %}
        <p class="text-center">No posts available.</p>
        {% endfor %}
    </div>
</div>

{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block content %}
{% if query %}
<h2>Post containing "{{ query }}"</h2>

<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>

{% for post in results %}
<h4>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h4>
{% empty %}
<p>There are no result for query.</p>
{% endfor %}
<p><a href="{% url 'blog:post_search'%}">Search again...</a></p>
{% else %}
<h1>Search for post</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

blog/templates/blog/post/share.html
<!-- blog/post/share.html -->
{% extends "blog/base.html" %}

{% block title %}Share Post{% endblock %}

{% block content %}
{% if sent %}
<div class="container mt-5">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">E-mail successfully sent!</h4>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    </div>
</div>
{% else %}
<div class="container mt-5">
    <h1 class="mb-4">Share "{{ post.title }}" by e-mail</h1>

    <form method="post" class="border p-4 rounded shadow-sm bg-light">
        {% csrf_token %}

        {% for field in form %}
        <div class="mb-3">
            <label class="form-label">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Send e-mail</button>
    </form>
</div>
{% endif %}
{% endblock %}

blog/templates/pagination.html
<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">

        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
        </li>
        {% endif %}

        <li class="page-item disabled">
            <a class="page-link">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </a>
        </li>

        {% if page.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
        </li>
        {% endif %}

    </ul>
</nav>